Create awu-ec-nomination-notice.en.md
alphabetworkers/alphabetworkersunion.org pull request #160
Opened 2022-07-05 18:22 UTC by shiibainu

Adding a new page for the nomination notice.

2022-07-07 01:22 UTC, jonahbron requested changes

2022-07-07 01:22 UTC, jonahbron commented on frontend/content/awu-ec-nomination-notice.en.md
> +<ol type="a">
Unless you verified this works locally, I'm pretty sure HTML directly in a markdown file will not work like this.  You can achieve this by using the literal "a. a hand-written ..." syntax.

2022-07-07 01:25 UTC, jonahbron approved these changes

2022-07-07 01:29 UTC, jonahbron requested changes

2022-07-07 01:29 UTC, jonahbron commented on frontend/content/awu-ec-nomination-notice.en.md
> +<ol type="a">
Unless you verified this works locally, I'm pretty sure HTML directly in a markdown file will not work like this. You can achieve this by using the literal "a. a hand-written ..." syntax.

2022-07-07 01:50 UTC, Dilnu commented
Looks right to me.

2022-07-07 01:55 UTC, shiibainu commented
Thanks Samuel! I think this is fine to merge if all else looks well.

2022-07-09 01:02 UTC, jonahbron requested changes

2022-07-09 01:02 UTC, jonahbron commented on frontend/content/_index.en.md
> +[Nomination notice for AWU Executive Council (2022-07-04)](awu-ec-nomination-notice.en.md)
I don't think this link will work out of the box.  You need the ref shortcode in markdown.

https://gohugo.io/content-management/cross-references/

2022-07-09 17:58 UTC, shiibainu commented on frontend/content/_index.en.md
> +[Nomination notice for AWU Executive Council (2022-07-04)](awu-ec-nomination-notice.en.md)
to make sure I understand correctly, does that mean I should replace the link with
({{< ref "awu-ec-nomination-notice.en.md" >}})
?

2022-07-12 02:55 UTC, jonahbron commented on frontend/content/_index.en.md
> +[Nomination notice for AWU Executive Council (2022-07-04)](awu-ec-nomination-notice.en.md)
Yes, I think that should work

2022-07-12 06:05 UTC, jonahbron approved these changes

2022-07-12 06:05 UTC, merged