Add TVC Share My Salary ULP
alphabetworkers/alphabetworkersunion.org pull request #201
Opened 2022-11-03 22:54 UTC by stephenmcmurtry

2022-11-03 23:08 UTC, realjenny requested changes

2022-11-03 23:08 UTC, realjenny commented on frontend/content/press/releases/tvc-salary-sharing-ulp.en.md
> +“Every worker has the right to share their salaries and wages in order to ensure that we are all getting our fair share. When we had access to a shared spreadsheet we could see how across companies,
The person doesn't need to be bolded

2022-11-03 23:08 UTC, realjenny commented on frontend/content/press/releases/tvc-salary-sharing-ulp.en.md
> +“Once again, Alphabet is violating its own commitments to end the practice of preventing workers from discussing their wages and other working conditions. It’s clear that Alphabet and its various aff
The person doesn't need to be bolded

2022-11-03 23:08 UTC, realjenny commented on frontend/content/press/releases/tvc-salary-sharing-ulp.en.md
> +In 2021, Temporary, Vendor and Contract (TVC) workers at Alphabet created a “Share My Salary” spreadsheet where contract workers across the globe could submit their job titles and hourly wages or sal
temporary, vendor, and contract

2022-11-03 23:22 UTC, realjenny approved these changes

2022-11-04 02:07 UTC, stephenmcmurtry commented on frontend/content/press/releases/tvc-salary-sharing-ulp.en.md
> +“Every worker has the right to share their salaries and wages in order to ensure that we are all getting our fair share. When we had access to a shared spreadsheet we could see how across companies,
Word. That's how Catalina sends them out, so wasn't sure if we needed to preserve that.

2022-11-04 02:20 UTC, merged