Applied copy change suggestions
alphabetworkers/alphabetworkersunion.org pull request #273
Opened 2024-08-25 04:15 UTC by jonahbron

2024-08-26 23:45 UTC, shiibainu commented
Reference doc with proposed changes: https://docs.google.com/document/d/1dn_tsG2eZ-wBPBdRay1lHeiCU6fjlDKehzIpTViiLxg/edit

2024-11-08 22:35 UTC, mattrubin requested changes
Instead of leaving comments wherever this code differed from the design doc, I just pushed some copy and style changes onto this PR.

2024-11-08 22:35 UTC, mattrubin commented on login/src/member-page.tsx
> +      return sources.data.filter((source) => source.object === 'bank_account').map(({ id }) => id);
@jonahbron It looks like this change would treat any bank account as legacy ACH. Is that intentional?

2025-09-16 20:26 UTC, mattrubin approved these changes

2025-09-16 20:26 UTC, merged