Applied feedback from Equity Committee
alphabetworkers/alphabetworkersunion.org pull request #34
Opened 2021-03-21 23:19 UTC by jonahbron

2021-03-21 23:47 UTC, realjenny requested changes

2021-03-21 23:47 UTC, realjenny commented on frontend/src/element/signup.ts
> +          If you have any trouble completing this form, you may instead contact
Delete "you may instead"

2021-03-21 23:47 UTC, realjenny commented on frontend/src/element/signup.ts
> +            >Used to calculate your union dues. Select the calculator icon if
Just checking, what's the aria-label for the calculator icon? Can we make sure to use the same name?

2021-03-25 21:51 UTC, butterflyhug approved these changes

2021-04-05 03:38 UTC, jonahbron commented on frontend/src/element/signup.ts
> +            >Used to calculate your union dues. Select the calculator icon if
"Compensation calculator"

2021-04-05 03:38 UTC, jonahbron commented on frontend/src/element/signup.ts
> +          If you have any trouble completing this form, you may instead contact
Done

2021-04-08 04:36 UTC, merged