Add Code of Conduct.
alphabetworkers/alphabetworkersunion.org pull request #58
Opened 2021-05-11 01:17 UTC by xavidotron

2021-05-11 13:25 UTC, butterflyhug approved these changes
This text references an appendix which is not included in this doc -- is that going to be added here or posted separately? Or if the appendix is not going to be published in a similar manner, then can we remove the references to it?

2021-05-13 02:37 UTC, xavidotron commented
Removed the reference to the appendix.

2021-05-13 11:17 UTC, butterflyhug approved these changes

2021-05-14 00:29 UTC, realjenny requested changes

2021-05-14 00:29 UTC, realjenny commented on frontend/content/principles/code-of-conduct.en.md
> +title: 'Code of Conduct'
lowercase conduct to match style on rest of the site

2021-05-14 00:29 UTC, realjenny commented on frontend/content/principles/code-of-conduct.en.md
> +linktitle: 'Code of Conduct'
lowercase conduct to match style on rest of the site

2021-05-14 00:29 UTC, realjenny commented on frontend/content/principles/code-of-conduct.en.md
> +## Anti-Harassment
Anti-harassment

2021-05-14 00:29 UTC, realjenny commented on frontend/content/principles/code-of-conduct.en.md
> +This code of conduct applies to all Alphabet Workers Union spaces and in interactions with and about members, including but not limited to conferences, chat clients such as Slack, email, file sharing
Change Slack to Discord

2021-05-14 00:29 UTC, realjenny commented on frontend/content/principles/code-of-conduct.en.md
> +## Platform Usage
Platform usage

2021-05-14 00:29 UTC, realjenny commented on frontend/content/principles/code-of-conduct.en.md
> +As such, Administrators or moderators may moderate for topicality or keeping groups appropriately focused, with enforcement being considered more strictly in groups with larger audiences.
lowercase administrators

2021-05-14 00:29 UTC, realjenny commented on frontend/content/principles/code-of-conduct.en.md
> +The foundation of our union organizing is in face-to-face conversations. It is generally expected that your first and primary points of contact will be with other members of your Workplace Unit, Work
workplace unit, working group, committee, or chapter.

2021-05-14 00:29 UTC, realjenny commented on frontend/content/principles/code-of-conduct.en.md
> +## Rights and Responsibilities
Rights and responsibilities

2021-05-14 00:29 UTC, realjenny commented on frontend/content/principles/code-of-conduct.en.md
> +All members in good standing have the following rights in the Union:
lowercase union

2021-05-14 00:29 UTC, realjenny commented on frontend/content/principles/code-of-conduct.en.md
> +* The right to Union support in cases of workplace mistreatment and for workers whose employment status is pending determination of any legal processes
lowercase union

2021-05-14 00:29 UTC, realjenny commented on frontend/content/principles/code-of-conduct.en.md
> +    * Does not guarantee a certain type of support that the Union can provide
lowercase union

2021-05-14 00:29 UTC, realjenny commented on frontend/content/principles/code-of-conduct.en.md
> +All members, both full and retired, are expected to:
To match the style for the rest of the page, can you capitalize the first word in each item in this list?

2021-05-14 00:29 UTC, realjenny commented on frontend/content/principles/code-of-conduct.en.md
> +As a reminder, AWU uses a mode of enforcement that aligns with restorative justice rather than punitive justice. The “Enforcements” section discusses this briefly.
AWU-CWA

2021-05-14 00:29 UTC, realjenny commented on frontend/content/principles/code-of-conduct.en.md
> +As a reminder, AWU uses a mode of enforcement that aligns with restorative justice rather than punitive justice. The “Enforcements” section discusses this briefly.
Delete "The “Enforcements” section discusses this briefly." because it's not part of this particular doc

2021-05-15 17:17 UTC, xavidotron commented on frontend/content/principles/code-of-conduct.en.md
> +As a reminder, AWU uses a mode of enforcement that aligns with restorative justice rather than punitive justice. The “Enforcements” section discusses this briefly.
This is referring to the "Enforcement" section above in this doc; tried to clarify.

2021-05-15 18:39 UTC, realjenny requested changes
Changes so far look great, but there are still some outstanding comments that need to be addressed.

2021-05-16 01:22 UTC, xavidotron commented
Ah, I misunderstood Github's "hidden comments" feature. Maybe I got them all this time?

2021-05-16 18:07 UTC, realjenny approved these changes

2021-05-29 23:12 UTC, merged