Create wins.en.md
alphabetworkers/alphabetworkersunion.org pull request #72
Opened 2021-07-08 01:06 UTC by realjenny

2021-07-11 01:42 UTC, butterflyhug approved these changes

2021-07-11 20:52 UTC, junefish commented on frontend/content/power/wins.en.md
> +## Data center workers: know our rights
should it be capitalised as "Know Our Rights"?

2021-07-11 20:53 UTC, junefish requested changes
see comment in-line

2021-07-13 01:50 UTC, realjenny commented on frontend/content/power/wins.en.md
> +## Data center workers: know our rights
No, because the rest of the heading isn't capitalized. We use sentence case style not title case

2021-07-13 01:57 UTC, junefish commented on frontend/content/power/wins.en.md
> +## Data center workers: know our rights
Okay!  I'd seen it in title case other places (e.g. emails) so wanted to check.

2021-07-13 01:57 UTC, junefish approved these changes

2021-07-13 01:58 UTC, realjenny commented on frontend/content/power/wins.en.md
> +## Data center workers: know our rights
Appreciate the eagle eye! It's something that is changing in the world of grammar over time.

2021-07-13 01:58 UTC, merged