Update campaigns.en.md
alphabetworkers/alphabetworkersunion.org pull request #73
Opened 2021-07-08 01:07 UTC by realjenny

2021-07-11 01:43 UTC, butterflyhug approved these changes

2021-07-11 20:50 UTC, junefish commented on frontend/content/power/campaigns.en.md
> -## Data center workers: know our rights
Should it be capitalised "Know Our Rights"?

2021-07-11 20:52 UTC, junefish requested changes
see comment in-line

2021-07-13 01:57 UTC, junefish commented on frontend/content/power/campaigns.en.md
> -## Data center workers: know our rights
nvm

2021-07-13 01:58 UTC, junefish commented
never mind

2021-07-13 01:58 UTC, junefish approved these changes

2021-07-13 01:59 UTC, merged